#!/bin/bash

function dossier(){
    for i in $(ls $1)
    do echo $2$i
	if test -d "$1/$i"
	then
	    dossier "$1/$i" " ${2}-  "
	fi
    done
    
}

if test $# == 1
then
    
    if test -d "$1"
    then
		dossier "$1" '|'
    fi
fi


